### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by sachin0606** [kuikuitage/mygit#1]
can you share me you qq id?

**Comment by kuikuitage** [comment]
sorry，i just see the message，but what can i do for you ?

**Comment by kuikuitage** [comment]
> can you share me you qq id?

sorry，i just see the message，but what can i do for you ?

**Comment by sachin0606** [comment]
just saw your old gits i needed your help in developing cc5000 and cc6000 STB develop environment support. can you guide me.

**Comment by kuikuitage** [comment]
> just saw your old gits i needed your help in developing cc5000 and cc6000 STB develop environment support. can you guide me.

I have not been doing STB for many years. The code is from the previous company, and the CC6000 project is actually not familiar to me, just uploaded。1211495535
